In [67]:
!pip install sklearn

Defaulting to user installation because normal site-packages is not writeable


In [66]:
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import DBSCAN
import matplotlib.pyplot as plt 


In [41]:
#!wget https://github.com/sajedi68/Machine_Learning/blob/main/FuelConsumption.csv
! wget https://github.com/sajedi68/Machine_Learning/blob/main/customer_Cluster.csv

'DOSKEY' is not recognized as an internal or external command,
operable program or batch file.
--2022-03-07 09:57:25--  https://github.com/sajedi68/Machine_Learning/blob/main/customer_Cluster.csv
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'customer_Cluster.csv.14'

     0K .......... .......... .......... .......... ..........  143K
    50K .......... .......... .......... .......... ..........  268K
   100K .......... .......... .......... .......... ..........  189K
   150K .......... .......... .......... .......... ..........  427K
   200K .......... .......... .......... ..                     360K=1.0s

2022-03-07 09:57:27 (231 KB/s) - 'customer_Cluster.csv.14' saved [237796]



In [43]:
#df = pd.read_csv("customer_Cluster.csv")
#df.head(5)

my_data = pd.read_csv("customer_Cluster.csv", delimiter=",")
my_data[0:5]


CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [44]:
from sklearn import preprocessing 
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['Female','Male'])
my_data.Gender = le_sex.transform(my_data.Gender)
my_data.head(5)


CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1       1   19                  15                      39
1           2       1   21                  15                      81
2           3       0   20                  16                       6
3           4       0   23                  16                      77
4           5       0   31                  17                      40

# Clustering with DBSCAN 

In [57]:
X = my_data[['Gender','Age','Annual Income (k$)','Spending Score (1-100)']].values
#X = my_data[['Age','Annual Income (k$)','Spending Score (1-100)']].values
X[0:5]

array([[ 1, 19, 15, 39],
       [ 1, 21, 15, 81],
       [ 0, 20, 16,  6],
       [ 0, 23, 16, 77],
       [ 0, 31, 17, 40]], dtype=int64)

In [61]:
epsilon = 15
minimumSamples = 7
db = DBSCAN(eps=epsilon, min_samples=minimumSamples).fit(X)
labels = db.labels_
print(labels)
np.histogram(labels)


[-1  0 -1  0 -1  0  1  0 -1  0 -1 -1  1  0  1  0  0  0  0 -1  0  0  1  0
  1  0  0  0  0  0  1  0  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  2  0  2  0  2  3  2  3  2  0  2  3  2  3  2  3  2  3  2  0  2
  3  2  0  2  3  2  3  2  3  2  3  2  3  2  3  2  3  2  3  2  3  2  3  2
  3  2  3  2  3  2  3  2  3  2  3  2  3  2  3  2 -1  2  3  2  3  2 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1]


(array([ 18,   0, 113,   0,   0,   8,   0,  34,   0,  27], dtype=int64),
 array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  1.4,  1.8,  2.2,  2.6,  3. ]))

In [62]:
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_clusters_

4

In [63]:
unique_labels = set(labels)
unique_labels

{-1, 0, 1, 2, 3}

## Data visualization

In [67]:
#colors = plt.cm.Spectral(np.linspace(0, 1, len(unique_labels)))

# Clustering with Hierachial 